# Generated by Django 5.0.4 on 2024-04-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='staus',
            new_name='status',
        ),
    ]
